- defaults:
    link:
      create: true
      relink: true
      force: true
 
- link:
    ~/.bash-git-prompt: 
      path: shell/bash-git-prompt
    ~/.grc: 
      path: shell/grc
      force: false
    ~/.aliases:
      path: shell/aliases
    ~/.bash_profile:
      path: shell/bash_profile
    ~/.bashrc:
      path: shell/bashrc
