- defaults:
    link:
      create: true
      relink: true
      force: true
 
- link:
    ~/.gitconfig:
      path: dev/git/gitconfig
    ~/.gitignore_global:
      path: dev/git/gitignore_global
    ~/.hgignore_global:
      path: dev/git/hgignore_global
    ~/.gitconfig_ssh:
      path: dev/git/gitconfig_ssh
