- defaults:
    link:
      create: true
      relink: true
      force: true
 
- link:
    ~/.gitconfig:
      path: development/git/gitconfig
    ~/.gitignore_global:
      path: development/git/gitignore_global
    ~/.hgignore_global:
      path: development/git/hgignore_global
