#!/usr/bin/env bash

#   CLOUDRC - enabled cloud SDKs and aliases
#
#     This script is a component of dotfiles
#       https://github.com/robertpeteuil/dotfiles
#
#     Robert Peteuil (c) 2018


cloudrcname=".cloudrc"
cloudrcnum="3.0.2"
cloudrcdate="2018-09-02"


###### FUNCTIONS
sourceIf () {
  if [ -e "$1" ]; then
    . "$1"
  fi
}


##### LOAD GLOBAL CLOUD CREDENTIALS
sourceIf "$HOME/.cloud/.cloud_config"


##### LOAD PROVIDER SPECIFIC SDK & ALIASES ON DEMAND

# LOAD AWS SPECIFIC RC FILE
cloud-init-aws () {
  sourceIf "$HOME/.cloudrc_aws"
}
alias init-aws='cloud-init-aws'
alias aws-init='cloud-init-aws'

# LOAD GCP SPECIFIC RC FILE
cloud-init-gcp () {
  sourceIf "$HOME/.cloudrc_gcp"
}
alias init-gcp='cloud-init-gcp'
alias gcp-init='cloud-init-gcp'

# LOAD AZURE SPECIFIC RC FILE
cloud-init-azure () {
  sourceIf "$HOME/.cloudrc_azure"
}
alias init-azure='cloud-init-azure'
alias azure-init='cloud-init-azure'

# SERVERLESS CLOUD FUNCTION PACKAGE
cloud-init-serverless () {
  # tabtab source for serverless package
  sourceIf /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.bash
  # tabtab source for sls package
  sourceIf /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.bash
}
alias init-serverless='cloud-init-serverless'
