#!/bin/bash
# cspell: disable
# shellcheck disable=SC1090,SC1091

##  BASH PROFILE
#
#   A component of https://github.com/robertpeteuil/dotfiles
#


###### VARS
export BASH_PROFILE_LOADED=1

sourceIf () {
  if [ -e "$1" ]; then
    . "$1"
  fi
}

pathIf () {
  if [ -d "$1" ] && [ "${PATH#*$1}" = "$PATH" ]; then
    PATH="$PATH:$1"
  fi
}

pathIfPre () {
  if [ -d "$1" ] && [ "${PATH#*$1}" = "$PATH" ]; then
    PATH="$1:$PATH"
  fi
}


# source bashrc, unless sh shell
# if [ "$SHELL" != "/bin/sh" ] && [ -f "$HOME/.bashrc" ]; then
if [ -z "$BASH_RC_LOADED" ] && [ -f "$HOME/.bashrc" ]; then
  . ~/.bashrc
fi

