#!/bin/bash
# cspell: disable
# shellcheck disable=SC1090,SC1091

##  BASH PROFILE
#
#   A component of https://github.com/robertpeteuil/dotfiles
#


sourceIf () {
  if [ -e "$1" ]; then
    . "$1"
  fi
}

pathIf () {
  if [ -d "$1" ] && [[ $PATH != *"$1"* ]]; then
    PATH="$PATH:$1"
  fi
}

pathIfPre () {
  if [ -d "$1" ] && [[ $PATH != *"$1"* ]]; then
    PATH="$1:$PATH"
  fi
}


if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi

