#!/bin/bash
# cspell: disable
# shellcheck disable=SC1090,SC1091

##  BASH PROFILE
#
#   A component of https://github.com/robertpeteuil/dotfiles
#

###### VARS
export BASH_PROFILE_LOADED=1

sourceIf() {
  local file="${1:-}"
  [ -n "$file" ] && [ -f "$file" ] && [ -r "$file" ] && . "$file"
}

pathIf() {
  local dir="${1:-}"
  [ -n "$dir" ] && [ -d "$dir" ] || return 0
  case ":$PATH:" in
    *":$dir:"*) ;;
    *) PATH="${PATH:+$PATH:}$dir" ;;
  esac
}

pathIfPre() {
  local dir="${1:-}"
  [ -n "$dir" ] && [ -d "$dir" ] || return 0
  case ":$PATH:" in
    *":$dir:"*) ;;
    *) PATH="$dir${PATH:+:$PATH}" ;;
  esac
}

# source bashrc, unless sh shell
if [ -z "$BASH_RC_LOADED" ] && [ -f "$HOME/.bashrc" ]; then
  . ~/.bashrc
fi

# vim: ft=bash
