#!/bin/bash
# cspell: disable
# shellcheck shell=bash
# shellcheck disable=SC1083

set -e

##  DOTFILES DOWNLOADER
#
#   A component of https://github.com/robertpeteuil/dotfiles
#

DOTFILES_REPO="robertpeteuil/dotfiles"
# must match $DOTFILES value set in zsh/.zshenv(13) and shell/bashrc(11)
DOTFILES_TARGET_DIR="$HOME/.dotfiles"

OS=$(uname -s)

if [ -d "$DOTFILES_TARGET_DIR" ]; then
  echo -e "ERROR: target dotfiles dir '${DOTFILES_TARGET_DIR}' exists.\n" >&2
  exit 1
fi

## INSTALL PREREQS
if ! [ -x "$(command -v git)" ]; then
  if [ "$OS" = 'Darwin' ]; then
    echo "installing: homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    echo "installing: git"
    brew install git
  elif [ "$OS" = 'Linux' ]; then
    sudo apt-get update -qq -y
    echo "installing: git"
    sudo apt-get install -y git
  fi
fi

## CLONE DOTFILES REPO
git clone --quiet --recursive --depth 1 "https://github.com/${DOTFILES_REPO}".git "$DOTFILES_TARGET_DIR"

## RUN DOTBOT INSTALLER
cd "$DOTFILES_TARGET_DIR" || exit 1
ssh-keyscan -H github.com >>~/.ssh/known_hosts
./install

# vim: ft=bash
