#!/usr/bin/env zsh
# cspell: disable

# Add directory to PATH if it exists and isn't already in PATH
pathIf() {
  local dir="${1:-}"
  [[ -n "$dir" && -d "$dir" ]] || return 0
  if (( ${path[(Ie)$dir]} == 0 )); then
    path+=("$dir")
  fi
}

pathIf "$@"
