#!/usr/bin/env zsh
# cspell: disable

# Source a readable regular file if it exists
sourceIf() {
  local file="${1:-}"
  [[ -n "$file" && -f "$file" && -r "$file" ]] && source "$file"
}

sourceIf "$@"
