console_title_template = '{{.PWD}}'
version = 3
final_space = true

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[palette]
  black = '#000000'
  black2 = '#111111'
  red = '#f7768e'
  green = '#9ece6a'
  green2 = '#41a6b5'
  yellow = '#e0af68'
  yellow2 = '#c4a000'
  orange='#ff9e64'
  magenta = '#bb9af7'
  magenta2='#9d7cd8'
  cyan = '#7dcfff'
  blue = '#7aa2f7'
  purewhite = '#ffffff'
  white = '#e4e4e4'
  white2 = '#c0caf5'
  grey = '#565f89'
  grey2 = '#283457'
  
# [ block ]
#   leading_diamond = ''

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  # PATH
  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    foreground = 'p:black'
    background = 'p:blue'
    powerline_symbol = ''
    template = ' {{ .Path }} '

    [blocks.segments.properties]
      home_icon = '~'
      style = 'powerlevel'
  
  ## PATH - PLAIN
  # [[blocks.segments]]
  #   type = 'path'
  #   style = 'plain'
  #   foreground = 'p:black'
  #   background = 'p:blue'
  #   # powerline_symbol = ''
  #   # trailing_diamond = ''
  #   template = ' {{ .Path }} '
  #   # foreground = '#e4e4e4'
  #   # leading_powerline_symbol = ''
  #   # leading_powerline_symbol = ''
  #   # leading_powerline_symbol = ''
  #   # background = '#3465a4'

  #   [blocks.segments.properties]
  #     home_icon = '~'
  #     style = 'full'

  # [[blocks.segments]]
  #   template = ''
  #   foreground = 'p:blue'
  #   background = 'p:black'
  #   type = 'text'
  #   style = 'plain'
  ## PATH - PLAIN END

  # GIT
  [[blocks.segments]]
    # template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    # foreground = '#000000'
    foreground = 'p:black'
    powerline_symbol = ''
    # background = '#4e9a06'
    background = 'p:green'
    type = 'git'
    style = 'powerline'
    # background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#c4a000{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#f26d50{{ end }}', '{{ if gt .Ahead 0 }}#89d1dc{{ end }}', '{{ if gt .Behind 0 }}#4e9a06{{ end }}']
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}', '{{ if gt .Ahead 0 }}p:cyan{{ end }}', '{{ if gt .Behind 0 }}p:green{{ end }}']

    [blocks.segments.properties]
      # branch_icon = ' '
      branch_icon = ''
      fetch_stash_count = false
      fetch_status = true
      fetch_upstream_icon = false

# RIGHT PROMPT
[[blocks]]
  type = 'prompt'
  alignment = 'right'

  # NODE
  [[blocks.segments]]
    type = 'node'
    foreground = 'p:purewhite'
    background = 'p:green'
    template = ' {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}  '
    style = 'powerline'
    invert_powerline = true
    powerline_symbol = ''
    # foreground = '#ffffff'
    # background = '#689f63'

    [blocks.segments.properties]
      fetch_version = true

  # GO
  [[blocks.segments]]
    type = 'go'
    foreground = '#111111'
    background = '#00acd7'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}  '
    style = 'powerline'
    invert_powerline = true
    powerline_symbol = ''

    [blocks.segments.properties]
      fetch_version = true

  # JULIA
  [[blocks.segments]]
    type = 'julia'
    foreground = '#111111'
    background = '#4063D8'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}  '
    style = 'powerline'
    invert_powerline = true
    powerline_symbol = ''

    [blocks.segments.properties]
      fetch_version = true

  # PYTHON
  [[blocks.segments]]
    type = 'python'
    foreground = 'p:black2'
    background = 'p:yellow'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}  '
    style = 'powerline'
    invert_powerline = true
    powerline_symbol = ''
    # foreground = '#111111'
    # background = '#FFDE57'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_virtual_env = false

  # RUBY
  [[blocks.segments]]
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}  '
    foreground = '#ffffff'
    powerline_symbol = ''
    background = '#AE1401'
    type = 'ruby'
    style = 'powerline'
    invert_powerline = true

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = true

  # AZFUNC
  [[blocks.segments]]
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#ffffff'
    powerline_symbol = ''
    background = '#FEAC19'
    type = 'azfunc'
    style = 'powerline'
    invert_powerline = true

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = false

  # AWS
  [[blocks.segments]]
    template = ' {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }}  '
    foreground = '#ffffff'
    powerline_symbol = ''
    type = 'aws'
    style = 'powerline'
    background_templates = ['{{if contains "default" .Profile}}#FFA400{{end}}', '{{if contains "jan" .Profile}}#f1184c{{end}}']
    invert_powerline = true

    [blocks.segments.properties]
      display_default = false

  # ROOT
  [[blocks.segments]]
    type = 'root'
    foreground = 'p:black2'
    background = 'p:orange'
    template = '  '
    style = 'powerline'
    invert_powerline = true
    powerline_symbol = ''
    # foreground = '#111111'
    # background = '#ffff66'

  # EXECUTION TIME
  [[blocks.segments]]
    type = 'executiontime'
    foreground = 'p:black'
    background = 'p:yellow'
    template = ' {{ .FormattedMs }}  '
    style = 'powerline'
    invert_powerline = true
    powerline_symbol = ''
    # foreground = '#000000'
    # background = '#c4a000'

    [blocks.segments.properties]
      style = "austin"

  # STATUS
  [[blocks.segments]]
    type = 'status'
    foreground_templates = ['{{ if gt .Code 0 }}p:black{{ else }}p:white{{ end }}']
    background_templates = ['{{ if gt .Code 0 }}p:red{{ else }}p:green2{{ end }}']
    template = ' {{ if gt .Code 0 }}{{ reason .Code }}{{ else }}{{ end }} '
    style = 'powerline'
    invert_powerline = true
    powerline_symbol = ''
    # background = '#000000'
    # background = 'p:grey2'
    # foreground = '#d3d7cf'
    # background_templates = ['{{ if gt .Code 0 }}#cc2222{{ end }}']

    [blocks.segments.properties]
      always_enabled = true

  # SESSION
  [[blocks.segments]]
    type = "session"
    foreground = "#ffffff"
    background = 'p:magenta2'
    template = "{{ if .SSHSession }} {{ .UserName }}@{{ .HostName }} {{ end }}"
    style = "diamond"
    leading_diamond = ''
    trailing_diamond = ""
    # template = "{{ if .SSHSession }}  {{ .UserName }}@{{ .HostName }} {{ end }}"

  # [[blocks.segments]]
  #   trailing_diamond = '─╮'
  #   template = ' {{ .CurrentDate | date .Format }}  '
  #   foreground = '#000000'
  #   background = '#d3d7cf'
  #   type = 'time'
  #   style = 'diamond'
  #   invert_powerline = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = 'p:blue'
    template = "❯"
    # template = ''
    # template = '╰─'

# [[blocks]]
#   type = 'rprompt'

#   [[blocks.segments]]
#     template = '─╯'
#     foreground = '#d3d7cf'
#     type = 'text'
#     style = 'plain'
