[theme]
name = "tokyo-night"
parent = "marine"

[colors]
# AlertInfo: alerting the user at an INFO level
AlertInfo = "#ffc777"

# AlertWarn: alerting the user at a WARN level
AlertWarn = "#ff9e64"

# AlertError: alerting the user at an ERROR level
AlertError = "#ff007c"

# Annotation: less-critical, supporting text
Annotation = "#b4f9f8"

# Base: default foreground color
Base = "#c0caf5"

# Guidance: instructing the user as help or context
Guidance = "#4fd6be"

# Important: drawing the user’s attention to information
Important = "#bb9af7"

# Title: titling a section or view
Title = "#3d59a1"

# Tokyo Night Palette
# #1f2335
# #24283b
# #292e42
# #3b4261
# #414868
# #545c7e
# #565f89
# #737aa2
# #a9b1d6
# #c0caf5
# #394b70
# #3d59a1
# #7aa2f7
# #7dcfff
# #b4f9f8
# #bb9af7
# #9d7cd8
# #ff9e64
# #ffc777
# #c3e88d
# #4fd6be
# #41a6b5
# #ff757f
# #c53b53
# #ff007c
