# .tmux.conf

### SESSION MANAGEMENT
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'
# dont restart any programs when restoring
set -g @resurrect-processes 'false'
set -g @resurrect-capture-pane-contents 'on'

### PLUGINS
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
run-shell ~/.tmux/plugins/tmux-continuum/continuum.tmux

# Adjust prompt for continuum (must be at very end, after run tpm)
continuum_auto_save='#(~/.tmux/plugins/tmux-continuum/scripts/continuum_save.sh)'
status_right="$status_right$continuum_auto_save"

